-- Support inbox table used by Contact Support and Admin Support Inbox pages
CREATE TABLE IF NOT EXISTS support_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved')),
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_support_messages_created_at ON support_messages (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_messages_status ON support_messages (status);

ALTER TABLE support_messages ENABLE ROW LEVEL SECURITY;

-- Allow signed-in users to create support requests
DROP POLICY IF EXISTS "Authenticated users can insert support messages" ON support_messages;
CREATE POLICY "Authenticated users can insert support messages"
ON support_messages FOR INSERT
WITH CHECK (auth.uid() IS NOT NULL);

-- Allow only admins to view all support requests
DROP POLICY IF EXISTS "Admins can view support messages" ON support_messages;
CREATE POLICY "Admins can view support messages"
ON support_messages FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
  )
);

-- Allow only admins to update ticket status/read state
DROP POLICY IF EXISTS "Admins can update support messages" ON support_messages;
CREATE POLICY "Admins can update support messages"
ON support_messages FOR UPDATE
USING (
  EXISTS (
    SELECT 1
    FROM profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
  )
);
